project:
  type: book

book:
  title: "How Stars Work"
  author: "Benjamin Pope"
  date: today
  date-format: "D MMMM YYYY"
  chapters:
    - index.qmd
    - housekeeping.qmd
    - hydrostatic-equilibrium.qmd
    - timescales.qmd
    - references.qmd
  search: true
  repo-url: https://github.com/benjaminpope/howstarswork/
  repo-actions: [edit]
  downloads: [pdf]
  sharing: [twitter, facebook]

bibliography: references.bib

format:
  html:
    theme: 
      dark: [darkly]
      light: cosmo
    grid:
      margin-width: 350px
  pdf:
    documentclass: scrreprt
    mainfont: Palatino

jupyter: python3

reference-location: margin
# citation-location: margin

toc: true
toc-title: Contents
execute:
  freeze: auto