project:
  type: book

book:
  title: "How Stars Work"
  author: "Benjamin Pope"
  date: today
  date-format: "D MMMM YYYY"
  chapters:
    - index.qmd
    - hydrostatic-equilibrium.qmd
    - references.qmd
  search: true
  repo-url: https://github.com/benjaminpope/howstarswork/
  repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  navbar:
    tools:
      - icon: twitter
        href: https://twitter.com/fringetracker
      - icon: bluesky
        href: https://bsky.app/profile/fringetracker.bsky.social

bibliography: references.bib

format:
  html:
    theme: 
      light: cosmo
      dark: [darkly]
    grid:
      margin-width: 350px
  pdf:
    documentclass: scrreprt
    mainfont: Times New Roman

reference-location: margin
citation-location: margin

toc: true
toc-title: Contents
execute:
  freeze: auto