# Hydrostatic Equilibrium
```{python}
#| echo: false
from constants import *
```

<!-- Tufte format from https://quarto-dev.github.io/quarto-gallery/page-layout/tufte.html  -->
The fundamental physics of stars is determined by a handful of principles: 

- the star is everywhere in pressure balance under its own gravity, or *hydrostatic equilibrium*; [hydrostatic from Greek ὕδωρ, 'water', and στάσις, 'standing'; just like water in a tank.]{.aside}
- its cooling by radiation must be met by 
    - *energy production* in its interior by nuclear fusion or gravitational contraction, 
    - and *energy transport* to its surface by radiation, convection, and conduction; 
- how its material responds to pressure (parametrized the *equation of state*) and to light (parametrized by *opacity*); and
- in its interior and a star is typically rotating and magnetic, which we will neglect in most of these notes.

Let's talk about hydrostatic equilibrium first.

<!-- Consider moving gas pressure to the end? -->

An ordinary star like the Sun, throughout its whole body, is to a very good approximation an *ideal gas*, and is fully ionized except in its outermost layer. This means that the gas pressure satisfies the equation of state

$$
\textcolor{blue}{p} = n \textcolor{red}{k_B} \textcolor{orange}{T}
$$
[where $\textcolor{blue}{p}$ is the <font color='blue'>pressure</font>, $n$ is the number density (particles per volume) of the gas, $\textcolor{red}{k_B}$ is <font color='red'>Boltzmann's constant</font> ($1.38\times10^{-16}$ erg/K), and $\textcolor{orange}{T}$ is the <font color='orange'>temperature</font> in kelvin.]{.aside}
<!-- https://www.overleaf.com/learn/latex/Using_colors_in_LaTeX colour link -->
In a star like the Sun, the pressure is mostly provided by gas pressure. In hotter stars, *photon* or *radiation pressure* is dominant, but in the Sun this is $\sim 10^{-3} p_\text{gas}$. 

Even in the Sun, though, the gas is not *quite* a classical ideal gas: quantum mechanics is already relevant. There is an equation we will derive later in these notes for the pressure due to the *degeneracy* of a gas where the quantum wavefunctions of its constituent particles are nearly overlapping: 

$$
p_\text{degeneracy} = \frac{\textcolor{purple}{\hbar}}{5\textcolor{green}{m_e}} (\frac{3}{8 \pi})^{2/3} n^{5/3}
$$
[where $\textcolor{purple}{\hbar}$ is the <font color='purple'>quantum of action $h/2\pi$</font> ($1.0546 \times 10^{-27} \text{erg}\cdot\text{s}$), and $\textcolor{green}{m_e}$ the <font color='green'>mass of the electron</font>.]{.aside}

It turns out this is about a quarter of the gas pressure at the core of the Sun! 

## The Equation of Hydrostatic Equilibrium

Consider a thin shell of radius $r$ (and surface area $A = 4\pi r^2$), thickness $dr$, and mass density $\rho$, enclosing a mass $M_r$[i.e. $M_r$ is the total mass integrated out up to a radius $r$.
]{.aside}. 

The mass of this shell is $M_\text{shell} = \rho A dr$, and from Newton's law of gravitation[[Newton's Shell Theorem](https://en.wikipedia.org/wiki/Shell_theorem) states that the gravitational attraction of a symmetric shell of matter, and therefore by linearity of a ball of matter, can be treated as if the mass were concentrated at a point at the centre. 
]{.aside} the magnitude of the gravitational force of the whole shell inwards is 

$$ 
\frac{- G M_r M_\text{shell}}{r^2}
$$

So now we can calculate the net force on this shell (and therefore acceleration $a$), and require the forces to be in balance:

$$
F_\text{net} = M_\text{shell} a = P_\text{below} \cdot A - P_\text{above} \cdot A - \frac{G M_r M_\text{shell}}{r^2}
$$

Letting $P_\text{above} = P_\text{below} + dP$, 

$$
M_\text{shell} a = a \rho A dr = - A dP  - \frac{G M_r M_\text{shell}}{r^2}
$$

and therefore rearranging, in equilibrium ($a = 0$) we have the __equation of hydrostatic equilibrium__:

$$ 
\frac{dP}{dr} = -\rho \frac{G M_r}{r^2}
$${#eq-hydrostatic-equilibrium}
[*Tattoo this equation on the back of your eyelids.*]{.aside}

<!-- Now we explain in relation to the Earth: 

- pressure under the sea
    - calculate 10m in the (incompressible) water = 1 atmosphere
- atmospheric lapse rate
    - illustrate with figure showing 322.5m Q1 tower, Everest, Kármán line
- plane-parallel solar atmospheric scale height 
-->

## Plane-Parallel Approximation

This is actually a very familiar equation that we encounter not just in first-year physics, but in everyday life. Nearly all the mass of the Earth is in its body, and only a bit less than a millionth in its atmosphere. So we can consider a situation where 

$$
r = R_{\textcolor{NavyBlue}{\oplus}} + \textcolor{green}{z}
$$
[where $\textcolor{green}{z}$ is the $\textcolor{green}{\text{height}}$ in the atmosphere $\llless R_\oplus$. We often denote astronomical bodies by traditional symbols: $\textcolor{NavyBlue}{\oplus}$ is the astronomical symbol for the $\textcolor{NavyBlue}{\text{Earth}}$, and $\textcolor{yellow}{\odot}$ the $\textcolor{yellow}{\text{Sun}}$. There are many other traditional symbols that are now rarely used.]{.aside}

We can now write this in familiar terms with the acceleration due to gravity as

$$ 
\frac{dP}{dh} = -\rho \cdot \underbrace{\frac{G M_r}{r^2}}_{{\equiv g \text{, constant}}}
$$

<!-- water -->


```{python}
#| echo: false
depth = f'{101325/1e3/9.8:.2f}'
```


If we are dealing with an incompressible liquid like water,[We can rearrange this to solve for the depth of water required to reach a gauge pressure $\Delta P \equiv P-P_0$: 
$$
z = - \frac{\Delta P}{\rho g}
$$
For $\rho_\text{water} = 1000 \text{kg\,m}^{-3}$, to get a 1 atmosphere ($=10^6$ Pa) gauge pressure requires `{python} depth` m of water.]{.aside} then $\rho$ is a constant and we simply have 

$$ 
P(z) = P_0 - \rho g z
$$

Things are different when your density depends on pressure. For an ideal gas, $P = n k_B T$ and $\rho = n \textcolor{OliveGreen}{\langle m \rangle}$[where $\textcolor{OliveGreen}{\langle m \rangle}$ is the $\textcolor{OliveGreen}{\text{mean molecular mass}}$, and $\textcolor{orange}{\text{isothermal}}$ means having the same temperature everywhere, from ἴσος, "same", and θέρμη, "heat".
]{.aside} - so we have an *equation of state* that we can use to solve for the vertical structure of an $\textcolor{orange}{\text{isothermal}}$ atmosphere:

<!-- mean molecular weight needs its own section 
Consider a gas of many species such that each has mass fraction $X_i$, atomic number $A_i$, and total mass density $\rho$: then

$$
n_i = \rho \frac{X_i}{A_i m_p}
$$

so 

$$
\begin{aligned}
P &= \sum_{i} n_i k_B T \\
&= \frac{\rho k_B T}{m_p} \sum_i \frac{X_i}{A_i}\\
&= \frac{\rho k_B T}{m_p \mu_\text{ions}} \rightarrow \frac{1}{\mu_\text{ions}} = \sum_i \frac{X_i}{A_i}
\end{aligned}
$$

So for a fully ionized plasma, we get $n_e = \sum_i Z_i n_i$, and $1/\mu_e = \sum_i Z_i X_i / A_i$, and we have that mean molecular masses add reciprocally like springs:

$$
\frac{1}{\mu} = \frac{1}{\mu_{e^-}} + \frac{1}{\mu_\text{ions}}
$$
-->

$$ 
\begin{aligned}
\frac{d}{dz} (n k_B T) &= - \langle m \rangle g n \\
\frac{dn}{dz} &= - \frac{\langle m \rangle g}{k_B T} \cdot N \\ 
n &= n_0 \exp{(- \frac{\langle m \rangle g}{k_B T} z)} \\
n &= n_0 \exp{- z/\textcolor{cyan}{h}}
\end{aligned}
$$ 

and we call 
$\textcolor{cyan}{h}$ the $\textcolor{cyan}{\text{scale height}}$ in the atmosphere. Let's calculate this for some interesting situations!

First let's try an isothermal Earth atmosphere:

```{python}
mol_earth = 28.964 * m_p # average molecular weight for earth's atmosphere
T_earth = 300 # K; room temperature
g_earth = 9.8 # m/s

h = k_B * T_earth / mol_earth / g_earth
```

```{python}
#| echo: false
q1 = 322.5
everest = 8849
```

This scale height of `{python} f'{(h/1e3):.1f}'` km is `{python} f'{h/R_earth * 1e3:.1f}'`$\,\times 10^{-3} R_\oplus$; the atmosphere really is very thin and can be treated as plane-parallel. This scale height would mean that the air is `{python} f'{(np.exp(-q1/h))*100:.0f}'`% as dense at the top of the $\textcolor{Maroon}{\text{Q1 Tower}}$, and `{python} f'{(np.exp(-everest/h))*100:.0f}'`% as dense at the summit of $\textcolor{gray}{\text{Mt Everest}}$.[$\textcolor{Maroon}{\text{Q1 Tower}}$ on the Gold Coast is the tallest tower in Australia, at $\textcolor{Maroon}{322.5}$ m; $\textcolor{gray}{\text{Mt Everest}}$, Earth's tallest mountain, stands $\textcolor{gray}{8849}$ m tall.]{.aside} 


Now let's plug in some numbers for the Sun, using Python:

```{python}
m = 0.5 * m_p # kg
# mean molecular weight for ionized hydrogen = 
# mean of electron & proton = m_p/2

g = G * M_sun / R_sun**2
h = k_B * Teff_sun / m / g
```

```{python}
#| echo: false
g_over_earth = f'{g/9.8:.1f}'
h_fraction = f'{h/R_sun * 1e4:.1f}'
```

giving a gravity $g =$ `{python} g_over_earth` Earth gravities, and a scale height of `{python} h_fraction`$\,\times 10^{-4}\,R_\odot$. So we see that the solar atmosphere has a _tiny_ scale height relative to the overall size of the Sun, and the plane-parallel approximation is even better than on Earth!

<!-- Then we explain the idea of scaling relations: how do we estimate the central pressure?

- derive idea that Pc / R = rho GM / R^2 
- estimate central mass of the Sun 
- discuss the general idea of scaling relations in this course: 
    - we are going to find relations for R, L, etc
 -->

## Scaling Relations

Most of the time, it is not possible to calculate properties of realistic stars in closed-form equations, and we will have to use computer models. But what *understanding* does this buy us? It is often just as important to have a sense of how these properties scale with one another in general terms, even if we might not be able to estimate actual numbers to better than an order of magnitude.

As a first example, let's estimate the pressure at the centre of the Sun. Ideally, we would solve for the full stellar structure using some equation of state, and then integrate $\frac{dP}{dr}$ from zero at the surface $r=R_\odot$ all the way to the core. Instead, we're going to do something very handwavy. Let's rearrange the $\frac{dP}{dr}$ in @{eq-hydrostatic-equilibrium} to instead be the mean gradient $P/R_\odot$:

$$
\begin{aligned}
\frac{dP}{dr} &= -\rho \frac{GM_r}{r^2} \\ 
\frac{P}{R_\odot} &\approx \langle \rho \rangle \frac{GM_\odot}{R_\odot^2}\\
P &\approx \langle \rho \rangle \frac{GM_\odot}{R_\odot}\\
&\approx \frac{M_\odot}{4/3 \pi R_\odot^3} \frac{GM_\odot}{R_\odot}\\
&\approx \frac{GM_\odot^2}{4/3 \pi R_\odot^4}
&\propto \frac{GM_\odot^2}{R_\odot^4}
\end{aligned}
$$
[Remarkably, it can be shown analytically [@Milne1936] that $P > \frac{GM^2}{8\pi R^4}$ for an arbitrary star - so we are not even *too* far from the exact solution with these mathematical sins. It is often the case that very coarse approximations differ from exact solutions by a factor of order unity; we will therefore often drop these factors and just think about the scaling.]{.aside}

```{python}
#| echo: false
P_sun = G * M_sun**2 / R_sun**4
```

which for the Sun, gives `{python} md_float(P_sun)` Pa pressure, which is within an order of magnitude of the central pressure of `{python} md_float(2.3e+16)` Pa in the Standard Solar Model [@Guenther1992].

We are going to do this kind of approximation a lot in these notes: to estimate how nuclear reactions scale with temperature, how stellar luminosities depend on mass, how stars form and how they die - and we will also tackle real computer models of these processes, so that we build both intuitive understanding and accurate models we can fit to data. Both are essential tools in astronomy. ["May God us keep From Single vision & Newtons sleep." — William Blake, Letter to Thomas Butts, 22 November 1802.]{.aside}

